name: ChuckNorrisFacts
options:
  bundleIdPrefix: evandro
  deploymentTarget: 
    iOS: "14.2"
  preGenCommand: killall Xcode || true
  postGenCommand: open ChuckNorrisFacts.xcodeproj -a Xcode && xcodegen dump --type graphviz --file Graph.dot 
  groupOrdering: 
    - order: [ExperimentTCA1]
packages:
  TCA:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.11.0
targets:
  ChuckNorrisFactsApp:
    type: application
    platform: iOS
    sources: [ChuckNorrisFactsApp]
    dependencies:
      - target: ChuckNorrisFactsCommon
      - target: FactsModule
      - target: SearchModule
  ChuckNorrisFactsCommon:
    type: framework
    platform: iOS
    sources: [ChuckNorrisFactsCommon]
    scheme:
      buildImplicitDependencies: false
    dependencies:
      - package: TCA
        product: ComposableArchitecture
  FactsModule:
    type: framework
    platform: iOS
    sources: [FactsModule]
    dependencies:
      - target: SearchModule
      - target: ChuckNorrisFactsCommon
  FactsModuleTests:
    type: bundle.unit-test
    platform: iOS
    sources: [FactsModuleTests]
    dependencies:
      - target: ChuckNorrisFactsCommon
      - target: FactsModule
  SearchModule:
    type: framework
    platform: iOS
    sources: [SearchModule]
    dependencies:
      - target: ChuckNorrisFactsCommon
  SearchModuleTests:
    type: bundle.unit-test
    platform: iOS
    sources: [SearchModuleTests]
    dependencies:
      - target: ChuckNorrisFactsCommon
      - target: SearchModule

schemes:
  ChuckNorrisFactsApp:
    build:
      targets:
        ChuckNorrisFactsApp: all
  FactsModule:
    build:
      targets:
        FactsModule: all
    test:
      targets: [FactsModuleTests]
      gatherCoverageData: true
      coverageTargets: 
        - FactsModule 
  SearchModule:
    build:
      targets:
        SearchModule: all
    test:
      targets: [SearchModuleTests]
      gatherCoverageData: true
      coverageTargets: 
        - SearchModule 